### PR TITLE
check if contractCall msg is Object before using `in` operator

### LINKED ISSUE #185: 🪲 Type error filtering contract call
### Prerequisites

* [x] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

While indexing smart contracts a type error occurs when trying to search a contract call inside a non object (see code line [here](https://github.com/subquery/subql-cosmos/blob/cd27f8d05ee48dfdc6db64c84b5c5de1357dad91/packages/node/src/utils/cosmos.ts#L95)).

<details>
<summary>Error message</summary>

Capture d’écran 2023-10-02 à 16 35 14

</details>

### Details

**Local Environment:** @subql/cli/3.5.1 darwin-arm64 node-v18.16.1
project branch: https://github.com/okp4/subql-okp4/tree/feat/add-proto-messages
block height: 2736323

### Steps to Reproduce

Simplest way to test would be to download the project branch and test directly

1. download code
2. install node modules
3. change block height
4. launch indexer

### PR DESCRIPTION
**Pull request by DeveloperInProgress**
# Description
check if it is safe to use `in` operator on decoded contract call msg data before trying to match it with contractCall filter using `in` operator

Fixes #185 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have tested locally
- [ ] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [ ] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

File: packages/node/src/utils/cosmos.ts [hunk 1]
```diff
@@ -92,7 +93,8 @@ export function filterMessageData(
     filter.contractCall &&
     !(
       filter.contractCall === data.msg.decodedMsg.msg ||
-      filter.contractCall in data.msg.decodedMsg.msg
+      (isObjectLike(data.msg.decodedMsg.msg) &&
```
Comment (stwiname) [inline packages/node/src/utils/cosmos.ts:96]: Can you please write a test for this please

**Review by stwiname — APPROVED** [review]

**Comment by stwiname** [comment]
@DeveloperInProgress can you please make a release with this fix
